import { Mentor, Investor, Course, BlogPost, Startup } from '@/types';

export const DEMO_USERS = [
  {
    id: '1',
    email: 'founder@zerotoone.com',
    password: 'Founder123',
    name: 'Arjun Sharma',
    role: 'founder' as const,
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=arjun',
    bio: 'Serial entrepreneur with 2 exits. Building the future of EdTech.',
    company: 'EduVerse',
    location: 'Bangalore, India',
    skills: ['Product Strategy', 'Fundraising', 'Team Building'],
    createdAt: '2024-01-15',
  },
  {
    id: '2',
    email: 'mentor@zerotoone.com',
    password: 'Mentor123',
    name: 'Priya Nair',
    role: 'mentor' as const,
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=priya',
    bio: 'Former CTO at unicorn startup. Mentor to 50+ founders.',
    company: 'Independent Advisor',
    location: 'Mumbai, India',
    skills: ['Tech Strategy', 'Product Management', 'Scaling'],
    createdAt: '2024-01-10',
  },
  {
    id: '3',
    email: 'investor@zerotoone.com',
    password: 'Investor123',
    name: 'Vikram Mehta',
    role: 'investor' as const,
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=vikram',
    bio: 'Partner at BlueSky Ventures. Invested in 30+ startups.',
    company: 'BlueSky Ventures',
    location: 'Delhi, India',
    skills: ['Due Diligence', 'Portfolio Management', 'Value Addition'],
    createdAt: '2024-01-08',
  },
  {
    id: '4',
    email: 'team@zerotoone.com',
    password: 'Team123',
    name: 'Sneha Patel',
    role: 'team' as const,
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=sneha',
    bio: 'Full-stack engineer passionate about startups.',
    company: 'EduVerse',
    location: 'Pune, India',
    skills: ['React', 'Node.js', 'Product Design'],
    createdAt: '2024-02-01',
  },
  {
    id: '5',
    email: 'admin@zerotoone.com',
    password: 'Admin123',
    name: 'Rahul Gupta',
    role: 'admin' as const,
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=rahul',
    bio: 'Platform administrator and ecosystem builder.',
    company: 'ZeroToOne',
    location: 'Hyderabad, India',
    skills: ['Platform Management', 'Community Building'],
    createdAt: '2024-01-01',
  },
];

export const MENTORS: Mentor[] = [
  {
    id: 'm1',
    name: 'Dr. Aisha Khan',
    title: 'Startup Advisor & Angel Investor',
    company: 'Khan Ventures',
    expertise: ['B2B SaaS', 'Product Strategy', 'Fundraising'],
    rating: 4.9,
    sessions: 287,
    hourlyRate: 4500,
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=aisha',
    bio: 'Former VP Product at Flipkart, now advising early-stage startups on growth and fundraising.',
    available: true,
    location: 'Bangalore',
  },
  {
    id: 'm2',
    name: 'Rajesh Iyer',
    title: 'Growth Hacker & Marketing Expert',
    company: 'GrowthLabs',
    expertise: ['Growth Marketing', 'D2C', 'Brand Strategy'],
    rating: 4.8,
    sessions: 412,
    hourlyRate: 3500,
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=rajesh',
    bio: 'Helped 100+ startups scale from 0 to ₹10Cr revenue through performance marketing.',
    available: true,
    location: 'Mumbai',
  },
  {
    id: 'm3',
    name: 'Sunita Reddy',
    title: 'FinTech Specialist & CFO Coach',
    company: 'FinStart Advisory',
    expertise: ['FinTech', 'Financial Modeling', 'Unit Economics'],
    rating: 4.7,
    sessions: 198,
    hourlyRate: 5000,
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=sunita',
    bio: 'Former CFO with expertise in financial planning for high-growth startups.',
    available: false,
    location: 'Hyderabad',
  },
  {
    id: 'm4',
    name: 'Amit Desai',
    title: 'Tech CTO & Architecture Expert',
    company: 'TechScale',
    expertise: ['Tech Architecture', 'Engineering Leadership', 'AI/ML'],
    rating: 4.9,
    sessions: 331,
    hourlyRate: 6000,
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=amit',
    bio: 'Built and scaled engineering teams at 3 unicorns. Now helping founders build robust tech.',
    available: true,
    location: 'Pune',
  },
  {
    id: 'm5',
    name: 'Kavitha Murthy',
    title: 'Operations & People Strategy',
    company: 'OpsFirst',
    expertise: ['Operations', 'HR Strategy', 'Culture Building'],
    rating: 4.6,
    sessions: 156,
    hourlyRate: 3000,
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=kavitha',
    bio: 'Helped 40+ startups build scalable operations and amazing company culture.',
    available: true,
    location: 'Chennai',
  },
  {
    id: 'm6',
    name: 'Nikhil Sharma',
    title: 'Legal & Compliance Advisor',
    company: 'StartupLaw Co.',
    expertise: ['Startup Law', 'IP Protection', 'Term Sheets'],
    rating: 4.8,
    sessions: 209,
    hourlyRate: 4000,
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=nikhil',
    bio: 'Structured 500+ deals for startups. Expert in fundraising legalities and ESOP planning.',
    available: true,
    location: 'Delhi',
  },
];

export const INVESTORS: Investor[] = [
  {
    id: 'i1',
    name: 'Deepak Goenka',
    firm: 'Nexus Venture Partners',
    type: 'VC Fund',
    portfolio: 47,
    stage: ['Seed', 'Series A'],
    sectors: ['SaaS', 'FinTech', 'EdTech'],
    minTicket: 5000000,
    maxTicket: 50000000,
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=deepak',
    bio: 'Backed by global LPs, investing in category-defining Indian startups.',
    location: 'Mumbai',
  },
  {
    id: 'i2',
    name: 'Ananya Singh',
    firm: 'Blume Ventures',
    type: 'Micro VC',
    portfolio: 82,
    stage: ['Pre-Seed', 'Seed'],
    sectors: ['D2C', 'AgriTech', 'HealthTech'],
    minTicket: 1000000,
    maxTicket: 15000000,
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=ananya',
    bio: 'First check investor with deep operational expertise in consumer companies.',
    location: 'Bangalore',
  },
  {
    id: 'i3',
    name: 'Ravi Krishnamurti',
    firm: 'IndiaQuotient',
    type: 'Angel Fund',
    portfolio: 35,
    stage: ['Pre-Seed', 'Seed', 'Series A'],
    sectors: ['Consumer', 'B2B SaaS', 'Deep Tech'],
    minTicket: 2000000,
    maxTicket: 20000000,
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=ravi',
    bio: 'Thesis-driven investor focused on India-specific problems and solutions.',
    location: 'Delhi',
  },
  {
    id: 'i4',
    name: 'Meera Kapoor',
    firm: 'WEH Ventures',
    type: 'Angel Network',
    portfolio: 23,
    stage: ['Pre-Seed'],
    sectors: ['Women-led', 'Social Impact', 'Education'],
    minTicket: 500000,
    maxTicket: 5000000,
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=meera',
    bio: 'Championing underrepresented founders building for Bharat.',
    location: 'Pune',
  },
  {
    id: 'i5',
    name: 'Siddharth Talwar',
    firm: 'Lightbox Ventures',
    type: 'Growth Fund',
    portfolio: 18,
    stage: ['Series A', 'Series B'],
    sectors: ['Consumer Internet', 'Marketplace', 'Retail Tech'],
    minTicket: 50000000,
    maxTicket: 500000000,
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=siddharth',
    bio: 'Long-term value creation partner for consumer internet businesses in India.',
    location: 'Mumbai',
  },
  {
    id: 'i6',
    name: 'Priyanka Joshi',
    firm: 'Kalaari Capital',
    type: 'VC Fund',
    portfolio: 56,
    stage: ['Seed', 'Series A', 'Series B'],
    sectors: ['HealthTech', 'CleanTech', 'Enterprise SaaS'],
    minTicket: 10000000,
    maxTicket: 100000000,
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=priyanka',
    bio: 'Technology-first investor with a track record of building category leaders.',
    location: 'Bangalore',
  },
];

export const COURSES: Course[] = [
  {
    id: 'c1',
    title: 'Startup Fundamentals: From Idea to MVP',
    description: 'Learn how to validate your startup idea, build your MVP, and find your first customers.',
    instructor: 'Arjun Kapoor',
    duration: '8 hours',
    lessons: 24,
    level: 'Beginner',
    category: 'Foundation',
    rating: 4.8,
    students: 12400,
    price: 2999,
    thumbnail: 'https://picsum.photos/seed/course1/400/250',
    tags: ['MVP', 'Idea Validation', 'Customer Discovery'],
  },
  {
    id: 'c2',
    title: 'Fundraising Mastery: Seed to Series A',
    description: 'Complete fundraising playbook from building investor deck to closing your first round.',
    instructor: 'Rohit Bansal',
    duration: '12 hours',
    lessons: 36,
    level: 'Intermediate',
    category: 'Fundraising',
    rating: 4.9,
    students: 8700,
    price: 4999,
    thumbnail: 'https://picsum.photos/seed/course2/400/250',
    tags: ['Fundraising', 'Pitch Deck', 'Investor Relations'],
  },
  {
    id: 'c3',
    title: 'Growth Hacking for Startups',
    description: 'Proven growth strategies used by unicorns to scale from 0 to 1 million users.',
    instructor: 'Sneha Verma',
    duration: '10 hours',
    lessons: 30,
    level: 'Intermediate',
    category: 'Growth',
    rating: 4.7,
    students: 15200,
    price: 3499,
    thumbnail: 'https://picsum.photos/seed/course3/400/250',
    tags: ['Growth Hacking', 'Marketing', 'User Acquisition'],
  },
  {
    id: 'c4',
    title: 'Building Product People Love',
    description: 'Product management framework for building products with strong PMF.',
    instructor: 'Kiran Rao',
    duration: '14 hours',
    lessons: 42,
    level: 'Advanced',
    category: 'Product',
    rating: 4.8,
    students: 9300,
    price: 5999,
    thumbnail: 'https://picsum.photos/seed/course4/400/250',
    tags: ['Product Management', 'PMF', 'User Research'],
  },
  {
    id: 'c5',
    title: 'Financial Modeling for Founders',
    description: 'Build investor-grade financial models and unit economics from scratch.',
    instructor: 'Meghna Gupta',
    duration: '6 hours',
    lessons: 18,
    level: 'Intermediate',
    category: 'Finance',
    rating: 4.6,
    students: 6800,
    price: 2499,
    thumbnail: 'https://picsum.photos/seed/course5/400/250',
    tags: ['Financial Modeling', 'Unit Economics', 'Forecasting'],
  },
  {
    id: 'c6',
    title: 'AI for Startups: Leverage AI to Scale 10x',
    description: 'Use AI tools and strategies to automate operations and scale faster.',
    instructor: 'Vikash Kumar',
    duration: '9 hours',
    lessons: 27,
    level: 'Beginner',
    category: 'AI & Technology',
    rating: 4.9,
    students: 21000,
    price: 3999,
    thumbnail: 'https://picsum.photos/seed/course6/400/250',
    tags: ['AI', 'Automation', 'ChatGPT', 'Tools'],
  },
];

export const BLOG_POSTS: BlogPost[] = [
  {
    id: 'b1',
    title: '10 Mistakes First-Time Founders Make (And How to Avoid Them)',
    slug: '10-mistakes-first-time-founders',
    excerpt: 'After analyzing 500+ startup failures, we identified the most common mistakes that kill early-stage startups before they can scale.',
    content: `## Introduction\n\nBuilding a startup is one of the hardest things you can do. After studying 500+ startup failures, we identified patterns that consistently doom early-stage companies.\n\n## Mistake 1: Not Validating the Problem\n\nMost founders fall in love with their solution before validating if the problem is real enough for people to pay to solve it.\n\n## Mistake 2: Building Too Early\n\nThe classic trap: spending 6 months building a product before talking to a single customer.\n\n## Mistake 3: Ignoring Unit Economics\n\nGrowing fast with negative unit economics is a recipe for disaster. Know your LTV:CAC ratio before scaling.\n\n## Mistake 4: The Wrong Co-Founder\n\nPicking a co-founder based on friendship rather than complementary skills is a common early mistake.\n\n## Mistake 5: Raising Too Early\n\nFundraising before finding PMF dilutes your equity and adds investor pressure at the wrong time.\n\n## Conclusion\n\nLearning from other founders' mistakes is one of the fastest ways to accelerate your own journey.`,
    author: 'Arjun Sharma',
    authorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=arjun',
    category: 'Founder Lessons',
    tags: ['Mistakes', 'Early Stage', 'PMF', 'Fundraising'],
    thumbnail: 'https://picsum.photos/seed/blog1/800/450',
    readTime: '8 min read',
    publishedAt: '2025-05-15',
    views: 24500,
    likes: 1847,
    featured: true,
  },
  {
    id: 'b2',
    title: 'How to Write a Winning Pitch Deck in 2025',
    slug: 'winning-pitch-deck-2025',
    excerpt: 'A step-by-step guide to creating a pitch deck that makes investors say yes in the first meeting.',
    content: `## What Makes a Great Pitch Deck\n\nAfter reviewing 300+ pitch decks, we break down exactly what investors look for in 2025.\n\n## Slide 1: Problem\n\nStart with a crisp problem statement. Use data. Make investors feel the pain.\n\n## Slide 2: Solution\n\nOne clear sentence explaining how you solve the problem differently.\n\n## Slide 3: Market Size\n\nShow TAM, SAM, SOM with credible sources.\n\n## Slide 4: Traction\n\nNumbers speak louder than words. Revenue, users, growth rate.\n\n## Conclusion\n\nA great pitch deck tells a compelling story backed by data and a clear path to scale.`,
    author: 'Priya Nair',
    authorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=priya',
    category: 'Fundraising',
    tags: ['Pitch Deck', 'Investors', 'Fundraising'],
    thumbnail: 'https://picsum.photos/seed/blog2/800/450',
    readTime: '12 min read',
    publishedAt: '2025-05-10',
    views: 18200,
    likes: 1234,
    featured: true,
  },
  {
    id: 'b3',
    title: 'India\'s Startup Ecosystem in 2025: Trends and Opportunities',
    slug: 'india-startup-ecosystem-2025',
    excerpt: 'Deep dive into the sectors that will produce India\'s next 10 unicorns and how to position your startup to ride the wave.',
    content: `## State of Indian Startups\n\nIndia now has 100+ unicorns and is the 3rd largest startup ecosystem globally.\n\n## Hot Sectors\n\n- B2B SaaS for global markets\n- AI-powered consumer applications\n- Climate tech and sustainability\n- Rural fintech and digital payments\n\n## Funding Trends\n\nAfter the funding winter of 2022-23, investors are back with renewed interest in profitable, capital-efficient businesses.\n\n## Opportunities\n\nThe biggest opportunities lie in solving uniquely Indian problems at massive scale.`,
    author: 'Vikram Mehta',
    authorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=vikram',
    category: 'Industry Insights',
    tags: ['India', 'Trends', 'Opportunities', 'Ecosystem'],
    thumbnail: 'https://picsum.photos/seed/blog3/800/450',
    readTime: '10 min read',
    publishedAt: '2025-05-05',
    views: 31000,
    likes: 2156,
    featured: false,
  },
  {
    id: 'b4',
    title: 'Product-Market Fit: How to Know When You\'ve Found It',
    slug: 'product-market-fit-guide',
    excerpt: 'The definitive guide to recognizing, measuring, and sustaining product-market fit for your startup.',
    content: `## Defining PMF\n\nPMF is when your product genuinely satisfies a strong market demand.\n\n## The Sean Ellis Test\n\nAsk users: "How would you feel if you could no longer use our product?" If 40%+ say "Very disappointed" - you might have PMF.\n\n## Quantitative Signals\n\n- Organic growth and word-of-mouth\n- Low churn rate (<5% monthly)\n- Strong NPS (>50)\n- Users returning without prompting\n\n## What To Do When You Have PMF\n\nOnce you find PMF, the focus shifts to scaling distribution, not product.`,
    author: 'Sneha Patel',
    authorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=sneha',
    category: 'Product',
    tags: ['PMF', 'Product', 'Growth', 'Metrics'],
    thumbnail: 'https://picsum.photos/seed/blog4/800/450',
    readTime: '9 min read',
    publishedAt: '2025-04-28',
    views: 14800,
    likes: 987,
    featured: false,
  },
  {
    id: 'b5',
    title: 'Building a Remote-First Startup Team That Actually Works',
    slug: 'remote-startup-team',
    excerpt: 'Lessons from 50+ remote-first startups on building culture, communication, and productivity across geographies.',
    content: `## The New Normal\n\nRemote teams are no longer a compromise — they're a competitive advantage when done right.\n\n## Hiring for Remote\n\nPrioritize self-starters, strong writers, and people with high accountability.\n\n## Communication Systems\n\nAsynchronous by default, synchronous by choice. Document everything.\n\n## Culture Building\n\nCulture is built through repeated behavior, not values posters on walls.\n\n## Tools Stack\n\nLinear for tasks, Notion for docs, Loom for async video, Slack for quick communication.`,
    author: 'Rahul Gupta',
    authorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=rahul',
    category: 'Team Building',
    tags: ['Remote', 'Team', 'Culture', 'Hiring'],
    thumbnail: 'https://picsum.photos/seed/blog5/800/450',
    readTime: '7 min read',
    publishedAt: '2025-04-20',
    views: 9400,
    likes: 673,
    featured: false,
  },
  {
    id: 'b6',
    title: 'How to Close Your First B2B SaaS Deal Without Any Sales Experience',
    slug: 'first-b2b-saas-deal',
    excerpt: 'A practical playbook for technical founders selling enterprise software for the first time.',
    content: `## The Founder-Led Sales Phase\n\nEvery startup goes through a phase where the founders must sell. Embrace it.\n\n## The Discovery Call Framework\n\nSpend 70% of the call asking questions, not pitching. Understand pain before presenting solutions.\n\n## Building the Pipeline\n\nLinkedIn outreach + warm intros + content marketing. Start with 50 conversations before patterns emerge.\n\n## Closing Techniques\n\nThe best close is a clear next step defined at every meeting. Always end with "What's the next step?"\n\n## Pricing Strategy\n\nCharge more than you think. Your price signals your value.`,
    author: 'Arjun Sharma',
    authorAvatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=arjun',
    category: 'Sales',
    tags: ['Sales', 'B2B', 'SaaS', 'Revenue'],
    thumbnail: 'https://picsum.photos/seed/blog6/800/450',
    readTime: '11 min read',
    publishedAt: '2025-04-15',
    views: 22100,
    likes: 1562,
    featured: false,
  },
];

export const STARTUPS: Startup[] = [
  {
    id: 's1',
    name: 'EduVerse',
    tagline: 'AI-powered personalized learning for K-12',
    description: 'EduVerse uses AI to create personalized learning paths for students, helping them master subjects at their own pace.',
    stage: 'Series A',
    industry: 'EdTech',
    fundingNeeded: 50000000,
    fundingRaised: 12000000,
    teamSize: 24,
    founderId: '1',
    location: 'Bangalore',
    createdAt: '2023-06-01',
    metrics: { revenue: 4500000, growth: 340, users: 125000, mrr: 850000 },
  },
  {
    id: 's2',
    name: 'HealthBridge',
    tagline: 'Connecting rural patients to urban specialists',
    description: 'Telemedicine platform bridging the gap between rural patients and specialist doctors through AI-assisted diagnostics.',
    stage: 'Seed',
    industry: 'HealthTech',
    fundingNeeded: 20000000,
    fundingRaised: 5000000,
    teamSize: 11,
    founderId: '1',
    location: 'Hyderabad',
    createdAt: '2023-09-15',
    metrics: { revenue: 980000, growth: 210, users: 45000, mrr: 180000 },
  },
  {
    id: 's3',
    name: 'AgriChain',
    tagline: 'Farm-to-fork supply chain for Indian agriculture',
    description: 'Blockchain-powered supply chain solution helping farmers get fair prices and reducing food waste.',
    stage: 'Pre-Seed',
    industry: 'AgriTech',
    fundingNeeded: 8000000,
    fundingRaised: 1500000,
    teamSize: 7,
    founderId: '1',
    location: 'Pune',
    createdAt: '2024-01-10',
    metrics: { revenue: 240000, growth: 85, users: 3200, mrr: 45000 },
  },
  {
    id: 's4',
    name: 'FinFlow',
    tagline: 'Smart invoice financing for MSMEs',
    description: 'AI-powered invoice discounting platform helping small businesses get instant working capital.',
    stage: 'Series A',
    industry: 'FinTech',
    fundingNeeded: 100000000,
    fundingRaised: 35000000,
    teamSize: 38,
    founderId: '1',
    location: 'Mumbai',
    createdAt: '2022-11-20',
    metrics: { revenue: 15000000, growth: 180, users: 8500, mrr: 2100000 },
  },
  {
    id: 's5',
    name: 'ClimateWise',
    tagline: 'Carbon tracking and offsetting for enterprises',
    description: 'Enterprise carbon footprint tracking, reporting, and offsetting platform aligned with ESG goals.',
    stage: 'Seed',
    industry: 'CleanTech',
    fundingNeeded: 25000000,
    fundingRaised: 7500000,
    teamSize: 16,
    founderId: '1',
    location: 'Delhi',
    createdAt: '2023-04-05',
    metrics: { revenue: 2200000, growth: 290, users: 420, mrr: 380000 },
  },
  {
    id: 's6',
    name: 'TalentBridge',
    tagline: 'AI-powered hiring for fast-growing companies',
    description: 'Intelligent recruitment platform that uses AI to match candidates with companies based on skills and culture fit.',
    stage: 'Series B',
    industry: 'HRTech',
    fundingNeeded: 200000000,
    fundingRaised: 120000000,
    teamSize: 85,
    founderId: '1',
    location: 'Bangalore',
    createdAt: '2021-08-12',
    metrics: { revenue: 48000000, growth: 120, users: 35000, mrr: 5800000 },
  },
];

export const FAQ_DATA = [
  {
    question: 'What is ZeroToOne?',
    answer: 'ZeroToOne is an AI-powered startup building, entrepreneurship learning, and business execution platform that helps aspiring founders transform ideas into successful businesses through validation, planning, mentorship, and fundraising support.',
  },
  {
    question: 'Who is ZeroToOne for?',
    answer: 'ZeroToOne is built for aspiring entrepreneurs, startup founders at any stage, mentors who want to guide startups, investors looking for deal flow, and startup team members who need execution tools.',
  },
  {
    question: 'Is ZeroToOne free to use?',
    answer: 'We offer a free Starter plan with limited features. Our paid plans start at ₹999/month and unlock the full platform including AI tools, mentor marketplace, and investor connect.',
  },
  {
    question: 'How does the AI Copilot work?',
    answer: 'The AI Copilot is trained on thousands of startup case studies and best practices. It provides actionable guidance on business strategy, product development, marketing, fundraising, and team building based on your specific context.',
  },
  {
    question: 'Can I connect with real investors on the platform?',
    answer: 'Yes! Our investor network includes 500+ verified angels, seed funds, and VCs. You can apply for investment through our platform after completing your startup profile and pitch deck.',
  },
  {
    question: 'How is the Mentor Marketplace different from other platforms?',
    answer: 'Our mentors are vetted founders and industry experts with proven track records. All sessions are structured around your startup challenges, and we match you with the most relevant mentor based on your stage and industry.',
  },
  {
    question: 'What is the Startup Academy?',
    answer: 'Startup Academy is our comprehensive learning platform with 100+ courses, bootcamps, and case studies covering every aspect of building a startup from ideation to exit.',
  },
  {
    question: 'How does idea validation work?',
    answer: 'Our AI-powered validation engine analyzes your startup idea across market demand, competition, feasibility, and timing. You get a detailed report with a validation score and actionable recommendations.',
  },
  {
    question: 'Can I manage multiple startups on one account?',
    answer: 'Yes, our Growth and Founder Pro plans support multi-startup management, allowing you to manage different ventures and their teams from a single dashboard.',
  },
  {
    question: 'Is my data secure on ZeroToOne?',
    answer: 'Absolutely. We use enterprise-grade encryption, secure data storage, and strict access controls. Your intellectual property and business data are protected and never shared without your consent.',
  },
];

export const SUCCESS_STORIES = [
  {
    id: 'ss1',
    founder: 'Priya Krishnan',
    startup: 'KiddieCare',
    amount: '₹12 Crore',
    round: 'Seed',
    description: 'Used ZeroToOne to validate her idea, build her pitch deck, and connect with investors. Closed seed round in 6 months.',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=priyak',
    industry: 'EdTech',
    year: '2024',
  },
  {
    id: 'ss2',
    founder: 'Rohan Malhotra',
    startup: 'LogiTrack',
    amount: '₹8 Crore',
    round: 'Pre-Seed',
    description: 'Found his technical co-founder and 3 key team members through ZeroToOne. Built MVP in 3 months and raised pre-seed.',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=rohan',
    industry: 'LogiTech',
    year: '2024',
  },
  {
    id: 'ss3',
    founder: 'Ishita Shah',
    startup: 'MindCare',
    amount: '₹5 Crore',
    round: 'Angel',
    description: 'Leveraged ZeroToOne mentors and AI copilot to refine product strategy. Onboarded 20,000 users before raising angel round.',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=ishita',
    industry: 'MentalHealth',
    year: '2023',
  },
  {
    id: 'ss4',
    founder: 'Abhishek Nair',
    startup: 'PropTech360',
    amount: '₹25 Crore',
    round: 'Series A',
    description: 'Used our Business Plan Builder and Financial Planning tools to create investor-grade documents that helped close Series A.',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=abhishek',
    industry: 'PropTech',
    year: '2024',
  },
  {
    id: 'ss5',
    founder: 'Divya Menon',
    startup: 'GreenBowl',
    amount: '₹3.5 Crore',
    round: 'Pre-Seed',
    description: 'Validated D2C food startup idea in 2 weeks using the AI engine. Connected with angel investors and closed round quickly.',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=divya',
    industry: 'FoodTech',
    year: '2023',
  },
  {
    id: 'ss6',
    founder: 'Sameer Khan',
    startup: 'SecureVault',
    amount: '₹40 Crore',
    round: 'Series A',
    description: 'Built the entire executive team through ZeroToOne matching. Scaled to ₹5Cr ARR before Series A in 18 months.',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=sameer',
    industry: 'CyberSecurity',
    year: '2024',
  },
];

export const TESTIMONIALS = [
  {
    id: 't1',
    name: 'Karan Mehta',
    role: 'Founder, CodeCraft',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=karan',
    quote: "ZeroToOne's AI Copilot is like having a world-class advisor available 24/7. It helped me pivot my business model at exactly the right time.",
    rating: 5,
  },
  {
    id: 't2',
    name: 'Neha Agarwal',
    role: 'Co-Founder, SkillUp',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=neha',
    quote: "I found my CTO co-founder through ZeroToOne's matching system. We've been building together for 18 months now. Best platform decision I made.",
    rating: 5,
  },
  {
    id: 't3',
    name: 'Vishal Rao',
    role: 'Founder, DataPulse',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=vishal',
    quote: 'The mentor marketplace connected me with exactly the right advisor at the right stage. Dr. Khan helped me navigate my first fundraise successfully.',
    rating: 5,
  },
  {
    id: 't4',
    name: 'Anjali Singh',
    role: 'Founder, WellnessApp',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=anjali',
    quote: 'The Startup Academy courses are incredibly practical. Not theoretical fluff — real tactics from founders who have done it.',
    rating: 5,
  },
];

export const CHART_DATA = {
  revenueData: [
    { month: 'Jan', revenue: 245000, target: 200000 },
    { month: 'Feb', revenue: 312000, target: 250000 },
    { month: 'Mar', revenue: 298000, target: 300000 },
    { month: 'Apr', revenue: 421000, target: 350000 },
    { month: 'May', revenue: 487000, target: 400000 },
    { month: 'Jun', revenue: 542000, target: 450000 },
    { month: 'Jul', revenue: 612000, target: 500000 },
    { month: 'Aug', revenue: 698000, target: 550000 },
    { month: 'Sep', revenue: 745000, target: 600000 },
    { month: 'Oct', revenue: 821000, target: 650000 },
    { month: 'Nov', revenue: 912000, target: 700000 },
    { month: 'Dec', revenue: 1045000, target: 750000 },
  ],
  userGrowth: [
    { month: 'Jan', users: 1200 },
    { month: 'Feb', users: 2100 },
    { month: 'Mar', users: 3400 },
    { month: 'Apr', users: 5200 },
    { month: 'May', users: 7800 },
    { month: 'Jun', users: 11000 },
    { month: 'Jul', users: 15400 },
    { month: 'Aug', users: 21200 },
    { month: 'Sep', users: 28700 },
    { month: 'Oct', users: 37500 },
    { month: 'Nov', users: 48200 },
    { month: 'Dec', users: 62000 },
  ],
  fundingData: [
    { round: 'Pre-Seed', amount: 1500000 },
    { round: 'Seed', amount: 5000000 },
    { round: 'Series A', amount: 12000000 },
    { round: 'Total', amount: 18500000 },
  ],
  channelData: [
    { name: 'Organic', value: 45 },
    { name: 'Referral', value: 28 },
    { name: 'Paid', value: 15 },
    { name: 'Social', value: 12 },
  ],
  startupHealthData: [
    { metric: 'Revenue', score: 82 },
    { metric: 'Growth', score: 91 },
    { metric: 'Team', score: 75 },
    { metric: 'Product', score: 88 },
    { metric: 'Market Fit', score: 79 },
    { metric: 'Runway', score: 65 },
  ],
  weeklyActivity: [
    { day: 'Mon', tasks: 8, meetings: 3 },
    { day: 'Tue', tasks: 12, meetings: 2 },
    { day: 'Wed', tasks: 6, meetings: 5 },
    { day: 'Thu', tasks: 15, meetings: 1 },
    { day: 'Fri', tasks: 9, meetings: 4 },
    { day: 'Sat', tasks: 4, meetings: 0 },
    { day: 'Sun', tasks: 2, meetings: 0 },
  ],
};
